---
title: "The Effect of Bank Size on the Realtionship between T1 Capital and Small-Business Lending"
output: html_notebook
---

### Read in Panel Data

```{r}
library(plm)

data <- readRDS("../panel_mdi_ind.rds")

panel <- pdata.frame(data, index = c("IDRSSD", "quarter"), drop.index=TRUE, row.names=TRUE)
```





## FE models:  T1 Leverage Ratio




### Change in $ Amount of Small Business Loans less than $100,000
```{r}
FEmodel1 <- plm(amt_CI_less_100_SB_loans_Delt ~  t1_LR_lagged_1_year + less_100_lagged_SB_loans_TA + ROA + NPA_TA + I(log(panel$total_assets_lagged_1_year)) + TD_TA + I(post_crisis_ind) + I(t1_LR_lagged_1_year * black_ind) + I(t1_LR_lagged_1_year * hispanic_ind), data = panel, model = "within", effect = "twoways")
summary(FEmodel1)
```













### Change in $ Amount of Small Business Loans from $100,000 to $250,000

```{r}
FEmodel2 <- plm(amt_CI_100_250_SB_loans_Delt ~  t1_LR_lagged_1_year + X100_250_lagged_SB_loans_TA + ROA + NPA_TA + I(log(panel$total_assets_lagged_1_year)) + TD_TA + I(post_crisis_ind) + I(t1_LR_lagged_1_year * black_ind) + I(t1_LR_lagged_1_year * hispanic_ind), data = panel, model = "within", effect = "twoways")
summary(FEmodel2)
```









### Change in $ Amount of Small Business Loans from $250,000 to $1,000,000

```{r}
FEmodel3 <- plm(amt_CI_250_1000_SB_loans_Delt ~  t1_LR_lagged_1_year + X250_1000_lagged_SB_loans_TA + ROA + NPA_TA + I(log(panel$total_assets_lagged_1_year)) + TD_TA + I(post_crisis_ind) + I(t1_LR_lagged_1_year * black_ind) + I(t1_LR_lagged_1_year * hispanic_ind), data = panel, model = "within", effect = "twoways")
summary(FEmodel3)
```

