---
title: "Test FE Models"
output: html_notebook
---

### Read in Panel Data

```{r}
library(plm)

data <- readRDS("../panel_mdi_ind.rds")

panel <- pdata.frame(data, index = c("IDRSSD", "quarter"), drop.index=TRUE, row.names=TRUE)
panel$totSBloans_Delt[ !is.finite(panel$totSBloans_Delt) ] <- NA

panel$TETA <- panel$total_equity_lagged_1_year / panel$total_assets_lagged_1_year

```

## FE models:  T1 Leverage Ratio
### Change in $ Amount of Total Small Business Loans 
```{r}
FEmodel1 <- plm(totSBloans_Delt ~  t1_LR_lagged_1_year + TETA + tot_lagged_SB_loans_TA + ROA + NPA_TA + I(log(panel$total_assets_lagged_1_year)) + TD_TA + I(post_crisis_ind) + I(t1_LR_lagged_1_year * black_ind) + I(t1_LR_lagged_1_year * hispanic_ind), data = panel, model = "within", effect = "twoways")
summary(FEmodel1)
```

## FE models:  T1 Risk-Based Capital Ratio
### Change in $ Amount of Total Small Business Loans 

```{r}
FEmodel2 <- plm(totSBloans_Delt ~  t1_RBCR_lagged_1_year + TETA + tot_lagged_SB_loans_TA + ROA + NPA_TA + I(log(panel$total_assets_lagged_1_year)) + TD_TA + I(post_crisis_ind) + I(t1_LR_lagged_1_year * black_ind) + I(t1_LR_lagged_1_year * hispanic_ind), data = panel, model = "within", effect = "twoways")
summary(FEmodel2)
```
