---
title: "Fixed-Effects Models"
author: "Matt Brigida"
output: html_document
runtime: shiny
---

Choose your inputs and click the run button.  The capital ratio, assets, and minority status inputs create a subset of the full panel based on the particular parameters.  The loan size input determines the model's dependent variable. 

The time it takes for the model to run is increasing in the number of firms in your subsample.  So if you choose a large subsample, you may have to wait a minute or two.

The model has both firm and time fixed effects ($\alpha_{it}$), and has the following specification:
\begin{equation}
\% \Delta SB\ Loans = \beta_1 (T1\ Lev.\ Ratio) + \beta_2 \frac{Amt.\ SB\ Loans}{TA} + \beta_3 ROA + \beta_4 \frac{NPA}{TA} + \beta_5 \frac{Deposits}{TA} + \beta_6 log(TA) + \beta_7 (post\ crisis) + \alpha_{it} + \epsilon_{it}
\end{equation}
where *SB* denotes "Small Business", *NPA* denotes "Non-Performing Assets", and *TA* denotes "Total Assets".  *post crisis* is an indicator variable for the years 2012---2015 inclusive.  The graphic below only shows the $\beta_1$ coefficient and p-value, as well as the $R^2$ and number of degrees of freedom.

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(plm)
library(ggplot2)
library(ggthemes)

panelOrig <- readRDS(url("https://github.com/Matt-Brigida/FFIEC_Call_Reports/blob/master/querying_data_and_analysis/analyses/panel_data_analysis/full_panel/panel_mdi_ind.rds?raw=true"))

panelOrig <- pdata.frame(panelOrig, index = c("IDRSSD", "quarter"), drop.index=TRUE, row.names=TRUE)
max_assets <- max(panelOrig$total_assets_lagged_1_year, na.rm = TRUE)
min_assets <- min(panelOrig$total_assets_lagged_1_year, na.rm = TRUE)

inputPanel(
    sliderInput("t1", "Capital Ratio", max=1, min=0, value = c(.05, .2), step = 0.01),
    sliderInput("size", "Total Assets ($'000s)", max=max_assets, min=min_assets, value = c(1000, 10000), step = 100),
    selectizeInput("model", "Small Business Loan Size", choices = c("Less $100,000" = 1,
                                                                  "$100,000 to $250,000" = 2,
                                                                  "$250,000 to $1,000,000" = 3)),
    selectizeInput("mdi_ind", "Minority Status", choices = c("All Banks" = 1,
                                                                  "African-American-Owned" = 2,
                                                                  "Hispanic-Owned" = 3)),    
    actionButton("do", "Run Model")
)

work <- eventReactive(input$do, {
    
    panel <- panelOrig[panelOrig$t1_LR_pre_2014_lagged_1_year > input$t1[1] & panelOrig$t1_LR_pre_2014_lagged_1_year < input$t1[2], ]
    panel <- panel[panel$total_assets_lagged_1_year > input$size[1] & panel$total_assets_lagged_1_year < input$size[2], ]
    if(input$mdi_ind == 2){
        panel <- panel[panel$black_ind == 1, ]
    } else {
        if(input$mdi_ind == 3){
            panel <- panel[panel$hispanic_ind == 1, ]
        }
    }

    if(input$model == 1){
        FEmodel1 <- plm(amt_CI_less_100_SB_loans_Delt ~  t1_LR_pre_2014_lagged_1_year + less_100_lagged_SB_loans_TA + ROA + NPA_TA + I(log(panel$total_assets_lagged_1_year)) + TD_TA + I(post_crisis_ind), data = panel, model = "within", effect = "twoways")
        result <- summary(FEmodel1)

    } else {
        if(input$model == 2){
            FEmodel2 <- plm(amt_CI_100_250_SB_loans_Delt ~  t1_LR_pre_2014_lagged_1_year + X100_250_lagged_SB_loans_TA + ROA + NPA_TA + I(log(panel$total_assets_lagged_1_year)) + TD_TA + I(post_crisis_ind), data = panel, model = "within", effect = "twoways")
            result <- summary(FEmodel2) 
        } else {
            FEmodel3 <- plm(amt_CI_250_1000_SB_loans_Delt ~  t1_LR_pre_2014_lagged_1_year + X250_1000_lagged_SB_loans_TA + ROA + NPA_TA + I(log(panel$total_assets_lagged_1_year)) + TD_TA + I(post_crisis_ind), data = panel, model = "within", effect = "twoways")
            result <- summary(FEmodel3)

        }
    }

    adjRsq <- result$r.squared[2]
    Rsq <- result$r.squared[1]
    slope <- as.numeric(result$coefficients[rownames(result$coefficients) == "t1_LR_pre_2014_lagged_1_year",][1])
    pVal <- as.numeric(result$coefficients[rownames(result$coefficients) == "t1_LR_pre_2014_lagged_1_year",][4])
    df <- result$df[2]
    
    if(input$model == 1){
    plot_y_upper_limit <- as.numeric(quantile(panel$amt_CI_less_100_SB_loans_Delt, .85, na.rm = TRUE))
    plot_y_lower_limit <- as.numeric(quantile(panel$amt_CI_less_100_SB_loans_Delt, .15, na.rm = TRUE))
    intercept <- mean(panel$amt_CI_less_100_SB_loans_Delt, na.rm = TRUE) - slope * mean(panel$t1_LR_pre_2014_lagged_1_year, na.rm = TRUE)

    ggplot(panel, aes(x = t1_LR_pre_2014_lagged_1_year, y = amt_CI_less_100_SB_loans_Delt)) + geom_point(aes(colour = ROA)) + scale_colour_gradient(low = "green") + theme_hc(bgcolor = "darkunica") + geom_density_2d() + ylim(plot_y_lower_limit, plot_y_upper_limit) + labs(title = paste0("Capital Ratio Coef: ", round(slope, 2), "| P-value: ", round(pVal, 2)), subtitle = paste0("R-sq: ", round(Rsq, 4), "| Adj-R-sq: ", round(adjRsq, 4), "| Deg. Freedom: ", round(df, 0)), x = "T1 Leverage Ratio", y = "Change in SB Loans (Less than $100,000)") + geom_abline(slope = slope, intercept = intercept)#  + theme_solarized()  + scale_colour_hc("darkunica")

    } else {
        if(input$model == 2){
            plot_y_upper_limit <- as.numeric(quantile(panel$amt_CI_100_250_SB_loans_Delt, .85, na.rm = TRUE))
            plot_y_lower_limit <- as.numeric(quantile(panel$amt_CI_100_250_SB_loans_Delt, .15, na.rm = TRUE))
            intercept <- mean(panel$amt_CI_100_250_SB_loans_Delt, na.rm = TRUE) - slope * mean(panel$t1_LR_pre_2014_lagged_1_year, na.rm = TRUE)

            ggplot(panel, aes(x = t1_LR_pre_2014_lagged_1_year, y = amt_CI_100_250_SB_loans_Delt)) + geom_point() + ylim(plot_y_lower_limit, plot_y_upper_limit) + labs(title = paste0("Capital Ratio Coef: ", round(slope, 2), "| P-value: ", round(pVal, 2)), subtitle = paste0("R-sq: ", round(Rsq, 4), "| Adj-R-sq: ", round(adjRsq, 4), "| Deg. Freedom: ", round(df, 0)), x = "T1 Leverage Ratio", y = "Change in SB Loans ($100,000 to $250,000)") + theme_solarized(light = TRUE) + geom_abline(slope = slope, intercept = intercept)

            } else {
                plot_y_upper_limit <- as.numeric(quantile(panel$amt_CI_250_1000_SB_loans_Delt, .85, na.rm = TRUE))
                plot_y_lower_limit <- as.numeric(quantile(panel$amt_CI_250_1000_SB_loans_Delt, .15, na.rm = TRUE))
                intercept <- mean(panel$amt_CI_250_1000_SB_loans_Delt, na.rm = TRUE) - slope * mean(panel$t1_LR_pre_2014_lagged_1_year, na.rm = TRUE)

                ggplot(panel, aes(x = t1_LR_pre_2014_lagged_1_year, y = amt_CI_250_1000_SB_loans_Delt)) + geom_point() + ylim(plot_y_lower_limit, plot_y_upper_limit) + labs(title = paste0("Capital Ratio Coef: ", round(slope, 2), "| P-value: ", round(pVal, 2)), subtitle = paste0("R-sq: ", round(Rsq, 4), "| Adj-R-sq: ", round(adjRsq, 4), "| Deg. Freedom: ", round(df, 0)), x = "T1 Leverage Ratio", y = "Change in SB Loans ($250,000 to $1 million)") + theme_solarized(light = TRUE) + geom_abline(slope = slope, intercept = intercept)

            }
        }
      })

    renderPlot({
work()
})

```
