---
title: "Test FE Models"
output: html_notebook
---

### Read in Panel Data

```{r}
library(plm)

data <- readRDS("../panel_mdi_ind_denovo.rds")

panel <- pdata.frame(data, index = c("IDRSSD", "quarter"), drop.index=TRUE, row.names=TRUE)
panel$totSBloans_Delt[ !is.finite(panel$totSBloans_Delt) ] <- NA

panel$TETA <- panel$total_equity_lagged_1_year / panel$total_assets_lagged_1_year

```

## FE models:  T1 Leverage Ratio
### Change in $ Amount of Total Small Business Loans 
```{r}

panel1 <- panel[, c("totSBloans_Delt", "t1_LR_lagged_1_year", "tot_lagged_SB_loans_TA", "ROA", "NPA_TA", "total_assets_lagged_1_year", "TD_TA", "post_crisis_ind", "black_ind", "hispanic_ind", "de_novo", "TETA")]

panel1 <- panel1[complete.cases(panel1), ]

## problem is lm() gets rid of NAs, and so is shorter than panel---first must complete.cases
panel1$TETA_resid_LR <- lm(panel1$TETA ~ panel1$t1_LR_lagged_1_year)$resid


FEmodel1 <- plm(totSBloans_Delt ~  t1_LR_lagged_1_year + TETA_resid_LR + tot_lagged_SB_loans_TA + ROA + NPA_TA + I(log(panel1$total_assets_lagged_1_year)) + TD_TA + I(post_crisis_ind) + I(t1_LR_lagged_1_year * black_ind) + I(t1_LR_lagged_1_year * hispanic_ind) + de_novo, data = panel1, model = "within", effect = "twoways")
summary(FEmodel1)
```

## FE models:  T1 Risk-Based Capital Ratio
### Change in $ Amount of Total Small Business Loans 

```{r eval = TRUE}

panel2 <- panel[, c("totSBloans_Delt", "t1_RBCR_lagged_1_year", "tot_lagged_SB_loans_TA", "ROA", "NPA_TA", "total_assets_lagged_1_year", "TD_TA", "post_crisis_ind", "black_ind", "hispanic_ind", "de_novo", "TETA")]

panel2 <- panel2[complete.cases(panel2), ]

## problem is lm() gets rid of NAs, and so is shorter than panel---first must complete.cases
panel2$TETA_resid_RBCR <- lm(panel2$TETA ~ panel2$t1_RBCR_lagged_1_year)$resid

FEmodel2 <- plm(totSBloans_Delt ~  t1_RBCR_lagged_1_year + TETA_resid_RBCR + tot_lagged_SB_loans_TA + ROA + NPA_TA + I(log(panel2$total_assets_lagged_1_year)) + TD_TA + I(post_crisis_ind) + I(t1_RBCR_lagged_1_year * black_ind) + I(t1_RBCR_lagged_1_year * hispanic_ind) + de_novo, data = panel2, model = "within", effect = "twoways")
summary(FEmodel2)
```
